name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Define environment variables
      run: |
        echo $(date +%s) > VERSION
    - name: Replace environment variables
      env:
        DOCKER_HUB_ADDRESS: ${{ secrets.DOCKER_HUB_ADDRESS }}
        ES_HOST: ${{ secrets.ES_HOST }}
        ES_VERITASVERIFY_PASSWORD: ${{ secrets.ES_VERITASVERIFY_PASSWORD }}
        ES_VERITASVERIFY_USER: ${{ secrets.ES_VERITASVERIFY_USER }}
      run: |
        export VERSION=$(cat VERSION)
        envsubst '${VERSION} ${DOCKER_HUB_ADDRESS} ${ES_HOST} ${ES_VERITASVERIFY_PASSWORD} ${ES_VERITASVERIFY_USER} ' <Deployment/deployment_template.yaml > Deployment/deployment.yaml
    - name: Login services
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        docker login --username mazzine -p $DOCKER_TOKEN
    - name: Build the Docker image
      env:
        DOCKER_HUB_ADDRESS: ${{ secrets.DOCKER_HUB_ADDRESS }}
      run: |
        docker build . --tag $DOCKER_HUB_ADDRESS:veritasverifyapi$(cat VERSION)
    - name: Push the Docker image
      env:
        DOCKER_HUB_ADDRESS: ${{ secrets.DOCKER_HUB_ADDRESS }}
      run: |
        docker push $DOCKER_HUB_ADDRESS:veritasverifyapi$(cat VERSION)
    - uses: danielr1996/kubectl-action@1.0.0
      name: Deploy
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
        # With simple Blue/Green Deployment
        args: apply -f Deployment/deployment.yaml -n projveritas  && kubectl rollout status deployment/veritasverifyapi-v$(cat VERSION) -n projveritas && kubectl delete deployment --selector 'app==veritasverifyapi,version!=v'$(cat VERSION) -n projveritas